### ISSUE TITLE
Plugin netbox-virtual-circuit-plugin does not provide a 'config' variable.

### ISSUE THREAD

**Issue by martydingo** [vapor-ware/netbox-virtual-circuit-plugin#8]
Hiya there,

I'm seeing issues trying to install the plugin.

Using PIP, Everything goes smoothly up until the point where I add the plugin to configuration.py and restart the Netbox services, with this reporting that it cannot import the module. I've added this to the local_requirements.txt then, and ran upgrade.sh, and that results in the same error after enabling in configuration.py

I then cloned the git, and ran the python3 setup.py install command, which install absolutely fine and the logging shows it's successfully built the egg and put it in the venv python dist-packages folder, however now it gets reported that Plugin netbox-virtual-circuit-plugin does not provide a 'config' variable.

I know this isn't true as I've gone and taken a look at the __init__.py, and I can see it there. However, I do have another plugin that installs absolutely fine, and has a similar thing to yourselves (in the way of the install method of using plugins, netbox_topology_viewer) so I'm sure there's something amiss here that's not clear in logs here. 

Here's the error log. 

```
May 15 14:11:10 ipam gunicorn[8515]: Traceback (most recent call last):
May 15 14:11:10 ipam gunicorn[8515]:   File "/srv/netbox/netbox/netbox/settings.py", line 661, in <module>
May 15 14:11:10 ipam gunicorn[8515]:     plugin_config = plugin.config
May 15 14:11:10 ipam gunicorn[8515]: AttributeError: module 'netbox-virtual-circuit-plugin' has no attribute 'config'
May 15 14:11:10 ipam gunicorn[8515]: During handling of the above exception, another exception occurred:
May 15 14:11:10 ipam gunicorn[8515]: Traceback (most recent call last):
May 15 14:11:10 ipam gunicorn[8515]:   File "/srv/netbox/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
May 15 14:11:10 ipam gunicorn[8515]:     worker.init_process()
May 15 14:11:10 ipam gunicorn[8515]:   File "/srv/netbox/venv/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 92, in init_process
May 15 14:11:10 ipam gunicorn[8515]:     super().init_process()
May 15 14:11:10 ipam gunicorn[8515]:   File "/srv/netbox/venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
May 15 14:11:10 ipam gunicorn[8515]:     self.load_wsgi()
May 15 14:11:10 ipam gunicorn[8515]:   File "/srv/netbox/venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
May 15 14:11:10 ipam gunicorn[8515]:     self.wsgi = self.app.wsgi()
May 15 14:11:10 ipam gunicorn[8515]:   File "/srv/netbox/venv/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
May 15 14:11:10 ipam gunicorn[8515]:     self.callable = self.load()
May 15 14:11:10 ipam gunicorn[8515]:   File "/srv/netbox/venv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
May 15 14:11:10 ipam gunicorn[8515]:     return self.load_wsgiapp()
May 15 14:11:10 ipam gunicorn[8515]:   File "/srv/netbox/venv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
May 15 14:11:10 ipam gunicorn[8515]:     return util.import_app(self.app_uri)
May 15 14:11:10 ipam gunicorn[8515]:   File "/srv/netbox/venv/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
May 15 14:11:10 ipam gunicorn[8515]:     mod = importlib.import_module(module)
May 15 14:11:10 ipam gunicorn[8515]:   File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
May 15 14:11:10 ipam gunicorn[8515]:     return _bootstrap._gcd_import(name[level:], package, level)
May 15 14:11:10 ipam gunicorn[8515]:   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
May 15 14:11:10 ipam gunicorn[8515]:   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
May 15 14:11:10 ipam gunicorn[8515]:   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
May 15 14:11:10 ipam gunicorn[8515]:   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
May 15 14:11:10 ipam gunicorn[8515]:   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
May 15 14:11:10 ipam gunicorn[8515]:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
May 15 14:11:10 ipam gunicorn[8515]:   File "/srv/netbox/netbox/netbox/wsgi.py", line 7, in <module>
May 15 14:11:10 ipam gunicorn[8515]:     application = get_wsgi_application()
May 15 14:11:10 ipam gunicorn[8515]:   File "/srv/netbox/venv/lib/python3.7/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
May 15 14:11:10 ipam gunicorn[8515]:     django.setup(set_prefix=False)
May 15 14:11:10 ipam gunicorn[8515]:   File "/srv/netbox/venv/lib/python3.7/site-packages/django/__init__.py", line 19, in setup
May 15 14:11:10 ipam gunicorn[8515]:     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
May 15 14:11:10 ipam gunicorn[8515]:   File "/srv/netbox/venv/lib/python3.7/site-packages/django/conf/__init__.py", line 76, in __getattr__
May 15 14:11:10 ipam gunicorn[8515]:     self._setup(name)
May 15 14:11:10 ipam gunicorn[8515]:   File "/srv/netbox/venv/lib/python3.7/site-packages/django/conf/__init__.py", line 63, in _setup
May 15 14:11:10 ipam gunicorn[8515]:     self._wrapped = Settings(settings_module)
May 15 14:11:10 ipam gunicorn[8515]:   File "/srv/netbox/venv/lib/python3.7/site-packages/django/conf/__init__.py", line 142, in __init__
May 15 14:11:10 ipam gunicorn[8515]:     mod = importlib.import_module(self.SETTINGS_MODULE)
May 15 14:11:10 ipam gunicorn[8515]:   File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
May 15 14:11:10 ipam gunicorn[8515]:     return _bootstrap._gcd_import(name[level:], package, level)
May 15 14:11:10 ipam gunicorn[8515]:   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
May 15 14:11:10 ipam gunicorn[8515]:   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
May 15 14:11:10 ipam gunicorn[8515]:   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
May 15 14:11:10 ipam gunicorn[8515]:   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
May 15 14:11:10 ipam gunicorn[8515]:   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
May 15 14:11:10 ipam gunicorn[8515]:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
May 15 14:11:10 ipam gunicorn[8515]:   File "/srv/netbox/netbox/netbox/settings.py", line 666, in <module>
May 15 14:11:10 ipam gunicorn[8515]:     "and point to the PluginConfig subclass.".format(plugin_name)
May 15 14:11:10 ipam gunicorn[8515]: django.core.exceptions.ImproperlyConfigured: Plugin netbox-virtual-circuit-plugin does not provide a 'config' variable. This should be defined in the plugin's __init__.py file and point to the PluginConfig
May 15 14:11:10 ipam gunicorn[8515]: [2020-05-15 13:11:10 +0000] [8525] [INFO] Worker exiting (pid: 8525)
```

**Comment by marcoceppi** [comment]
Thanks for the issue. This is still a pretty early version of the plugin I'll see if @hoanhan101 can help get you sorted

**Comment by hoanhan101** [comment]
@martydingo Thanks for the issue. Happy to assist this. Is it possible for you to provide some more information so that I can replicate your issue myself?

Which operation system were you using, Netbox version as well as the plugin version?
Were you using Docker?

After installing the latest version of the plugin via pip
```python
pip install netbox-virtual-circuit-plugin
```
did you update the `configuration.py` like so?
```python
PLUGINS = ['netbox_virtual_circuit_plugin'] # Note that the name here use underscore, not hyphen.
```

If after adding `netbox_virtual_circuit_plugin` to `local_requirements.txt` and running `/opt/netbox/upgrade.sh` did not work, can you try applying the migration directly like so
```
python3 /opt/netbox/netbox/manage.py migrate
python3 /opt/netbox/netbox/manage.py collectstatic --no-input
```
then restart netbox?

Let me know if this works.

**Comment by martydingo** [comment]
I'm using Netbox 2.8.4 with netbox-virtual-circuit-plugin 0.1.2. It's not dockerized, it's a standard install on a VM running Debian 10, the only thing different then from the tutorial is the location (I like to put applications that serve content in /srv, whereas Netbox references /opt as default)

I'm using the Git method from the master repo of Netbox.

I've updated the configuration as such, and the error stops Netbox from loading whenever enabled in the configuration.py file as you've listed, which is no different then from what I'm attempting. 

Configuration is like so.

```
PLUGINS = [
  'netbox_topology_views',
  'netbox-virtual-circuit-plugin',
]

```
So, my flow would be, 

1. source /srv/netbox/venv/bin/activate

2. `pip install netbox-virtual-circuit-plugin` (whereis pip results in pip: /srv/netbox/venv/bin/pip /srv/netbox/venv/bin/pip3.7). In this case I've already installed it. (Requirement already satisfied: netbox-virtual-circuit-plugin in ./venv/lib/python3.7/site-packages (0.1.2))

3. /srv/netbox/upgrade.sh -- With the entry in configuration.py, it fails with the error `(LookupError: No installed app with label 'netbox-virtual-circuit-plugin'.)`, otherwise this runs successfully with the `netbox-virtual-circuit-plugin` commented. 

4. If I run the manage.py migrate command (`python3 /srv/netbox/netbox/manage.py migrate`) with the correct entry in configuration.py, it results in the same error above. 
` LookupError: No installed app with label 'netbox-virtual-circuit-plugin'. ` 
This error does not appear with the `netbox-virtual-circuit-plugin` commented. 

Now, if I install the plugin (So via PIP, and then an entry in configuration.py, no other configuration needed since we're not needing to configure the plugin further), and then restart the netbox service, I get the following.

``` 
May 17 11:43:39 ipam gunicorn[2019]:   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
May 17 11:43:39 ipam gunicorn[2019]:   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
May 17 11:43:39 ipam gunicorn[2019]:   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
May 17 11:43:39 ipam gunicorn[2019]:   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
May 17 11:43:39 ipam gunicorn[2019]:   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
May 17 11:43:39 ipam gunicorn[2019]:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
May 17 11:43:39 ipam gunicorn[2019]:   File "/srv/netbox/netbox/netbox/wsgi.py", line 7, in <module>
May 17 11:43:39 ipam gunicorn[2019]:     application = get_wsgi_application()
May 17 11:43:39 ipam gunicorn[2019]:   File "/srv/netbox/venv/lib/python3.7/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
May 17 11:43:39 ipam gunicorn[2019]:     django.setup(set_prefix=False)
May 17 11:43:39 ipam gunicorn[2019]:   File "/srv/netbox/venv/lib/python3.7/site-packages/django/__init__.py", line 19, in setup
May 17 11:43:39 ipam gunicorn[2019]:     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
May 17 11:43:39 ipam gunicorn[2019]:   File "/srv/netbox/venv/lib/python3.7/site-packages/django/conf/__init__.py", line 76, in __getattr__
May 17 11:43:39 ipam gunicorn[2019]:     self._setup(name)
May 17 11:43:39 ipam gunicorn[2019]:   File "/srv/netbox/venv/lib/python3.7/site-packages/django/conf/__init__.py", line 63, in _setup
May 17 11:43:39 ipam gunicorn[2019]:     self._wrapped = Settings(settings_module)
May 17 11:43:39 ipam gunicorn[2019]:   File "/srv/netbox/venv/lib/python3.7/site-packages/django/conf/__init__.py", line 142, in __init__
May 17 11:43:39 ipam gunicorn[2019]:     mod = importlib.import_module(self.SETTINGS_MODULE)
May 17 11:43:39 ipam gunicorn[2019]:   File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
May 17 11:43:39 ipam gunicorn[2019]:     return _bootstrap._gcd_import(name[level:], package, level)
May 17 11:43:39 ipam gunicorn[2019]:   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
May 17 11:43:39 ipam gunicorn[2019]:   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
May 17 11:43:39 ipam gunicorn[2019]:   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
May 17 11:43:39 ipam gunicorn[2019]:   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
May 17 11:43:39 ipam gunicorn[2019]:   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
May 17 11:43:39 ipam gunicorn[2019]:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
May 17 11:43:39 ipam gunicorn[2019]:   File "/srv/netbox/netbox/netbox/settings.py", line 666, in <module>
May 17 11:43:39 ipam gunicorn[2019]:     "and point to the PluginConfig subclass.".format(plugin_name)
May 17 11:43:39 ipam gunicorn[2019]: django.core.exceptions.ImproperlyConfigured: Plugin netbox-virtual-circuit-plugin does not provide a 'config' variable. This should be defined in the plugin's __init__.py file and point to the PluginConfig
May 17 11:43:39 ipam gunicorn[2019]: [2020-05-17 10:43:39 +0000] [2023] [INFO] Worker exiting (pid: 2023)
May 17 11:43:39 ipam gunicorn[2019]: Traceback (most recent call last):
May 17 11:43:39 ipam gunicorn[2019]:   File "/srv/netbox/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 202, in run
May 17 11:43:39 ipam gunicorn[2019]:     self.manage_workers()
May 17 11:43:39 ipam gunicorn[2019]:   File "/srv/netbox/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 545, in manage_workers
May 17 11:43:39 ipam gunicorn[2019]:     self.spawn_workers()
May 17 11:43:39 ipam gunicorn[2019]:   File "/srv/netbox/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 617, in spawn_workers
May 17 11:43:39 ipam gunicorn[2019]:     time.sleep(0.1 * random.random())
May 17 11:43:39 ipam gunicorn[2019]:   File "/srv/netbox/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
May 17 11:43:39 ipam gunicorn[2019]:     self.reap_workers()
May 17 11:43:39 ipam gunicorn[2019]:   File "/srv/netbox/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
May 17 11:43:39 ipam gunicorn[2019]:     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
May 17 11:43:39 ipam gunicorn[2019]: gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
May 17 11:43:39 ipam gunicorn[2019]: During handling of the above exception, another exception occurred:
May 17 11:43:39 ipam gunicorn[2019]: Traceback (most recent call last):
May 17 11:43:39 ipam gunicorn[2019]:   File "/srv/netbox/venv/bin/gunicorn", line 10, in <module>
May 17 11:43:39 ipam gunicorn[2019]:     sys.exit(run())
May 17 11:43:39 ipam gunicorn[2019]:   File "/srv/netbox/venv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 58, in run
May 17 11:43:39 ipam gunicorn[2019]:     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
May 17 11:43:39 ipam gunicorn[2019]:   File "/srv/netbox/venv/lib/python3.7/site-packages/gunicorn/app/base.py", line 228, in run
May 17 11:43:39 ipam gunicorn[2019]:     super().run()
May 17 11:43:39 ipam gunicorn[2019]:   File "/srv/netbox/venv/lib/python3.7/site-packages/gunicorn/app/base.py", line 72, in run
May 17 11:43:39 ipam gunicorn[2019]:     Arbiter(self).run()
May 17 11:43:39 ipam gunicorn[2019]:   File "/srv/netbox/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 229, in run
May 17 11:43:39 ipam gunicorn[2019]:     self.halt(reason=inst.reason, exit_status=inst.exit_status)
May 17 11:43:39 ipam gunicorn[2019]:   File "/srv/netbox/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 342, in halt
May 17 11:43:39 ipam gunicorn[2019]:     self.stop()
May 17 11:43:39 ipam gunicorn[2019]:   File "/srv/netbox/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 393, in stop
May 17 11:43:39 ipam gunicorn[2019]:     time.sleep(0.1)
May 17 11:43:39 ipam gunicorn[2019]:   File "/srv/netbox/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
May 17 11:43:39 ipam gunicorn[2019]:     self.reap_workers()
May 17 11:43:39 ipam gunicorn[2019]:   File "/srv/netbox/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
May 17 11:43:39 ipam gunicorn[2019]:     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
May 17 11:43:39 ipam gunicorn[2019]: gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
May 17 11:43:39 ipam systemd[1]: netbox.service: Main process exited, code=exited, status=1/FAILURE
```

**Comment by hoanhan101** [comment]
As I mentioned above, your `configuration.py` should like like this instead:
```python
PLUGINS = ['netbox_virtual_circuit_plugin'] # Note that the name here use underscore, not hyphen.
```
If you take a look at other plugins, you”ll see the same naming pattern as they use underscores for their Django app that is to be included in the configuration file, and hyphen for their package name that is to be published on pypi.

Let me know if that fixes it.

**Comment by martydingo** [comment]
Thanks very much, that's sorted it.
